# Generated by Django 6.0.7 on 2026-07-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alternatif', '0001_initial'),
        ('kriteria', '0002_alter_kriteria_bobot'),
        ('subkriteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alternatif.alternatif')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kriteria.kriteria')),
                ('subkriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subkriteria.subkriteria')),
            ],
        ),
    ]
