# Generated by Django 6.0.7 on 2026-07-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kriteria', '0002_alter_kriteria_bobot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=100)),
                ('skor', models.IntegerField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kriteria.kriteria')),
            ],
        ),
    ]
