# Generated by Django 6.0.7 on 2026-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.IntegerField()),
                ('jenis', models.CharField(choices=[('Benefit', 'Benefit'), ('Cost', 'Cost')], max_length=10)),
            ],
        ),
    ]
