# Generated by Django 6.0.7 on 2026-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
