# Generated by Django 6.0.7 on 2026-08-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=200)),
                ('pemilik', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('luas', models.CharField(max_length=100)),
                ('tahun_berdiri', models.PositiveIntegerField()),
                ('komoditas', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
